// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Load.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Load::Load(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::loader.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void Load::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void Load::Execute() {
//	while(Robot::loader.get()->i < 100){
	//	Robot::loader.get()->i++;//pause for 2 seconds for launcher to spin at beginning
	//}
		Robot::loader.get()->loadItDude();
}

// Make this return true when this Command no longer needs to run execute()
bool Load::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void Load::End() {
	Robot::loader.get()->stop();
	Robot::loader.get()->i = 0;
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Load::Interrupted() {
	End();
}
